# Load and read the data

In [47]:
import pandas as pd

df = pd.read_json('data_TCI.json', orient ='split', compression = 'infer')#orient ='split'
len(df)

30701

In [25]:
amount_over1G = ['1G', '2G', '5G', '10G', '25G', '50G', '90G', '100G', '200G', '250G', '300G',\
                 '400G', '500G', '1KG', '20MG', '100MG']

In [98]:
import numpy as np

df_1G = df[   (df['1G'].notnull())   | (df['2G'].notnull())   | (df['5G'].notnull()) |\
              (df['10G'].notnull())  | (df['25G'].notnull())  | (df['50G'].notnull()) |\
              (df['90G'].notnull())  | (df['100G'].notnull()) | (df['200G'].notnull()) |\
              (df['250G'].notnull()) | (df['300G'].notnull()) | (df['400G'].notnull()) |\
              (df['500G'].notnull()) | (df['1KG'].notnull())  | (df['20MG'].notnull()) |\
              (df['100MG'].notnull()) ]

In [101]:
df_identifiers = df_1G[['name', 'CAS', 'grade', 'reaxys registry number', 'pubchem substance id',\
      'merck index (14)', 'mdl number', 'sdbs (aist spectral db)',  'related cas rn',\
      'colour index', 'enzyme commission number']]
df_identifiers

,name,CAS,grade,reaxys registry number,pubchem substance id,merck index (14),mdl number,sdbs (aist spectral db),related cas rn,colour index,enzyme commission number
A0001,Abietic Acid,514-10-3,None,2221451.0,87561707.0,7.0,mfcd03423567,1471.0,None,NaN,None
A0002,Ethyl Abietate,631-71-0,None,NaN,87561708.0,NaN,mfcd00028860,NaN,None,NaN,None
A0003,Acenaphthene,83-32-9,None,386081.0,87561709.0,28.0,mfcd00003807,863.0,None,NaN,None
A0004,Acenaphthenequinone,82-86-0,None,879172.0,87561710.0,NaN,mfcd00003805,3313.0,None,NaN,None
A0005,Acenaphthylene,208-96-8,None,774092.0,87561711.0,NaN,mfcd00003806,1349.0,None,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...
C2154,Carbon Nanotube Multi-walled,308068-56-6,None,NaN,87559340.0,NaN,None,NaN,None,NaN,None
C2155,Carbon Nanotube Multi-walled,308068-56-6,None,NaN,87559341.0,NaN,None,NaN,None,NaN,None
C2156,Carbon Nanotube Multi-walled,308068-56-6,None,NaN,87559342.0,NaN,None,NaN,None,NaN,None
C2157,Carbon Nanotube Multi-walled,308068-56-6,None,NaN,87559343.0,NaN,None,NaN,None,NaN,None
C2158,Carbon Nanotube Multi-walled,308068-56-6,None,NaN,87559344.0,NaN,None,NaN,None,NaN,None

In [102]:
df_stock = df_1G[['1G', '2G', '5G', '10G', '25G', '50G', '90G', '100G', '200G', '250G', '300G',\
      '400G', '500G', '1KG', '20MG', '100MG']]
df_stock

,1G,2G,5G,10G,25G,50G,90G,100G,200G,250G,300G,400G,500G,1KG,20MG,100MG
A0001,None,None,None,None,"{'Stock in other WH': '20', 'price': '6,200', ...",None,None,None,None,None,None,None,"{'Stock in other WH': 'Contact Company', 'pric...",None,None,None
A0002,None,None,None,None,"{'Stock in other WH': '20', 'price': '14,800',...",None,None,None,None,None,None,None,None,None,None,None
A0003,None,None,None,None,"{'Stock in other WH': 'Contact Company', 'pric...",None,None,"{'Stock in other WH': 'Contact Company', 'pric...",None,None,None,None,"{'Stock in other WH': 'Contact Company', 'pric...",None,None,None
A0004,None,None,None,None,"{'Stock in other WH': '20', 'price': '14,800',...",None,None,"{'Stock in other WH': '20', 'price': '48,800',...",None,None,None,None,None,None,None,None
A0005,None,None,"{'Stock in other WH': 'Contact Company', 'pric...",None,"{'Stock in other WH': 'Contact Company', 'pric...",None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C2154,"{'Hyogo (Amagasaki)': 'Contact Company', 'pric...",None,"{'Hyogo (Amagasaki)': 'Contact Company', 'pric...",None,None,None,None,None,None,None,None,None,None,None,None,None
C2155,"{'Hyogo (Amagasaki)': '2', 'price': '9,300', '...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
C2156,"{'Hyogo (Amagasaki)': '10', 'price': '8,800', ...",None,"{'Hyogo (Amagasaki)': 'Contact Company', 'pric...",None,None,None,None,None,None,None,None,None,None,None,None,None
C2157,"{'Hyogo (Amagasaki)': '1', 'price': '9,300', '...",None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
C2158,"{'Hyogo (Amagasaki)': 'Contact Company', 'pric...",None,"{'Hyogo (Amagasaki)': '1', 'price': '25,700', ...",None,None,None,None,None,None,None,None,None,None,None,None,None

In [105]:
df_properties = df_1G[['Molecular Formula', 'Molecular Weight', 'purity / analysis method', 'appearance',  
                       'solubility in water', 'molecular weight', 'sensitiveness', 'average active oxygen', \
                       'the average value of n', 'the average value of m+n', 'the average value of (n+m)', \
                       'content(na,drying substance)',  'etherification value( as drying substance)', \
                       'cw (scheduled material type)', 'assay of mono ester',  'assay of diester' ]]
df_properties

,Molecular Formula,Molecular Weight,purity / analysis method,appearance,solubility in water,molecular weight,sensitiveness,average active oxygen,the average value of n,the average value of m+n,the average value of (n+m),"content(na,drying substance)",etherification value( as drying substance),cw (scheduled material type),assay of mono ester,assay of diester
A0001,C__2__0H__3__0O__2,302.46,>80.0%(gc),white to light yellow powder to crystal,practically insoluble,None,None,None,None,None,None,None,None,None,None,None
A0002,C__2__2H__3__4O__2,330.51,>80.0%(gc),colorless to yellow to green clear liquid,None,None,None,None,None,None,None,None,None,None,None,None
A0003,C__1__2H__1__0,154.21,>99.0%(gc),white to almost white powder to crystal,None,None,None,None,None,None,None,None,None,None,None,None
A0004,C__1__2H__6O__2,182.18,>98.0%(gc),light yellow to brown to dark green powder to ...,None,None,None,None,None,None,None,None,None,None,None,None
A0005,C__1__2H__8,152.2,>94.0%(gc),light yellow to brown powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C2154,None,None,None,black powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None
C2155,None,None,None,black powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None
C2156,None,None,None,black powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None
C2157,None,None,None,black powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None
C2158,None,None,None,black powder to crystal,insoluble,None,None,None,None,None,None,None,None,None,None,None

In [107]:
df_transportation = df_properties = df_1G[['Shipment Information', 'un number', 'Packaging and container',\
                                           'packing group',  'class', 'air transportation']]
df_transportation

,Shipment Information,un number,Packaging and container,packing group,class,air transportation
A0001,Prompt shipment (for products) in Saitama/Hyog...,un3077,None,iii,9.0,None
A0002,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
A0003,Prompt shipment (for products) in Saitama/Hyog...,un3077,None,iii,9.0,None
A0004,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
A0005,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
...,...,...,...,...,...,...
C2154,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
C2155,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
C2156,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
C2157,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None
C2158,Prompt shipment (for products) in Saitama/Hyog...,None,None,None,None,None